exParcial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tareasApp.urls'))
]

tareasApp/urls.py
from django.urls import path
from . import views

app_name = 'tareasApp'

urlpatterns = [

    path('', views.indice, name='indice'),
    path('nuevaTarea', views.nuevaTarea, name='nuevaTarea'),
]

tareasApp/models.py
from django.db import models

# Create your models here.

class tareas(models.Model):
    nombre = models.CharField(max_length=32, null=True, blank=True)
    descripcion = models.CharField(max_length=32, null=True, blank=True)
    fechaFin = models.CharField(max_length=32, null=True, blank=True)
    estadoTarea = models.CharField(max_length=32, null=True, blank=True)
    responsableTarea = models.CharField(max_length=32, null=True, blank=True)

tareasApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import tareas

# Create your views here.

def indice(request):

    tareasTotales = tareas.objects.all()
    return render(request, 'indice.html', {

        'tareasTotales': tareasTotales

    })

def nuevaTarea(request):

    if request.method == 'POST':

        print(request.POST)
        nombre = request.POST.get('nombre')
        descripcion = request.POST.get('descripcion')
        fechaFin = request.POST.get('fechaFin')
#        estadoTarea = request.POST.get('estadoTarea')
        estadoTarea = 'EN PROGRESO'
        responsableTarea = request.POST.get('responsableTarea')

        tareaCreada = tareas.objects.create(

            nombre = nombre,
            descripcion = descripcion,
            fechaFin = fechaFin,
            estadoTarea = estadoTarea,
            responsableTarea = responsableTarea

        )

        return HttpResponseRedirect(reverse('tareasApp:indice'))
    
    return render(request, 'nuevaTarea.html')

tareasApp/templates/indice.html
<!DOCTYPE html>
<html>

    <head>

        <title>Gestor de tareas</title>
        <style>

            table{

                width: 80%;
                border-collapse: collapse;
                background-color:skyblue;

            }

            table, th, td{

                border: 1px solid;
                height: 25px;
                text-align: center;
                font-family: Helvetica, sans-serif;
                
            }

        </style>

    </head>

    <body>

        <div style="text-align: center; font-family: Helvetica, sans-serif;">
        
            <h1>VISTA PRINCIPAL - GESTOR DE TAREAS</h1>

        </div>

        <div style="display: flex; flex-direction: row; justify-content: space-around;">

            <a href="{% url 'tareasApp:nuevaTarea' %}">

                <button style="width: 120px; height: 25px;">Nueva tarea</button>

            </a>

            <a>

                <button style="width: 120px; height: 25px;">Ver historico</button>
                
            </a>

        </div>

        <br>

        <div style="display: flex; flex-direction: row; justify-content: center;">

            <table id="tablaTareas">

                <thead>

                    <th>Nombre</th>
                    <th>Fecha de fin</th>
                    <th>Estado</th>
                    <th>Responsable</th>
                    <th>Finalizar</th>

                </thead>

                <tbody>

                    {% for tareaInfo in tareasTotales %}

                    <tr>
                        
                        <td id="tareaId" hidden>{{tareaInfo.id}}</td>
                        <td>{{tareaInfo.nombre}}</td>
                        <td>{{tareaInfo.fechaFin}}</td>
                        <td>{{tareaInfo.estadoTarea}}</td>
                        <td>{{tareaInfo.responsableTarea}}</td>
                        <td><button>Finalizar</button></td>

                    </tr>

                    {% endfor %}

                </tbody>

            </table>

        </div>

    </body>

</html>

tareasApp/templates/nuevaTarea.html
<!DOCTYPE html>
<html>

    <head>

        <title>Crear nueva tarea</title>

        <style>

            .etiquetas{

                font-family: Helvetica, sans-serif;
                
            }

        </style>

    </head>

    <body>

        <div style="text-align: center; font-family: Helvetica, sans-serif;">
        
            <h1>CREAR NUEVA TAREA</h1>

        </div>

        <br>

        <div>

            <a href="{% url 'tareasApp:indice' %}">

                <button style="height: 25px; margin-left: 200px;">Regresar</button>

            </a>

        </div>

        <br>

        <div class="etiquetas" style="display: flex; flex-direction: row; justify-content: center;">

            <form style="display: flex; flex-direction: row; width: 100%; justify-content: center;" method="post" action="{% url 'tareasApp:nuevaTarea' %}">

                {% csrf_token %}

                <div style="width: 60%;">

                    <div style="display: flex; flex-direction: row; justify-content: space-between; height: 60%;">

                        <div style="display: flex; flex-direction: column; width: 45%;">

                            <label style="height: 30px;">Nombre</label>
                            <input type="text" name="nombre" required>

                        </div>

                        <div style="display: flex; flex-direction: column; width: 45%;">

                            <label style="height: 30px;">Descripcion</label>
                            <input type="text" name="descripcion" required>

                        </div>

                    </div>

                    <div style="display: flex; flex-direction: row; justify-content: space-between; height: 60%;">

                        <div style="display: flex; flex-direction: column; width: 45%;">

                            <label style="height: 30px;">Fecha de fin</label>
                            <input type="date" name="fechaFin" required>

                        </div>

                        <div style="display: flex; flex-direction: column; width: 45%;">

                            <label style="height: 30px;">Responsable</label>
                            <input type="text" name="responsableTarea" required>

                        </div>

                    </div>

                    <br>

                    <div>

                        <input style="height: 25px;" type="submit" value="Crear tarea">

                    </div>

                </div>

            </form>

        </div>

    </body>

</html>